# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      image:
        required: true
        description: 'docker image name'
      sha-tag:
        required: true
        description: 'docker image tag'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ubuntu:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Obtain Latest Git ONLY within container for checkout
        run: |
          apt-get update
          apt-get install -y git curl
          
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        if: ${{ github.event.inputs.image }}
      
      - uses: fregante/setup-git-token@v1
        if: ${{ github.event.inputs.image }}
        with:
          token: ${{ secrets.CI_TOKEN }}
          name: BeerLii
          email: 735964033@qq.com
      
      - name: kustomize edit
        if: ${{ github.event.inputs.image }}
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          ls -al
          chmod +x kustomize
          ./kustomize edit set image ${{ github.event.inputs.image }}:${{ github.event.inputs.sha-tag }}
          rm -f kustomize
          git config --global --add safe.directory /__w/argocd-kustomize/argocd-kustomize
          git add .
          git commit -m "test"
          git push origin

#      - name: check status
#        if: ${{ github.event.inputs.image }}
#        run: |
#          cat kustomization.yaml
#          ls -al
#
#
#      - name: Git Commit/Push Changes
#        uses: actions-x/commit@v2
#        if: ${{ github.event.inputs.image }}
#        with:
#          message: "kustomize set image to ${{ github.event.inputs.image }}:${{ github.event.inputs.sha-tag }}"
